
==========================================================================
==============CloudOne Network Security Info for PoC/demo ==========
==========================================================================

- This section is applied if you specified [ deploy_c1ns = true ] in your cloudone-settings section in terraform.tfvars file

- C1NS is deployed following to Option 1: https://cloudone.trendmicro.com/docs/network-security/option1/

- Provisioned Diagram can be found at: docs/diagram/c1ns.jpg

- On AWS:
  + Network Firewall, Firewall Policy, Firewall rule groups are deployed
  + Cloudwatch log-groups for AWS Firewall
  + Cloudwatch log-groups for trendmicro-ips

- AWS Firewall will be used for Threat Sharing demo (https://cloudone.trendmicro.com/docs/network-security/share_threat_intel/)
  + in AWS Mgmt console > VPC > Firewall, choose the provisioned Firewall (c1ns-aws-firewall)
  + add Stateful Rule groups (networksecurity-snort-mrs-snort-rules-json)
  + Provisoned CloudWatch log-groups: trendmicro-aws-firewall-logs

- admin-vpc is protected VPC. There is 1 public subnet & NAT gateway so 1 C1NS Applicance is deployed. This VPC contains 2 EC2:
  + Windows 2019 Victim host: This EC2 is placed in an admin-vpc public subnet
    - Public IP: ${WIN-VICTIM-PUBIP}
    - Private IP: ${WIN-VICTIM-PRIVIP}
    - Hostname: ${WIN_VICTIM_HOSTNAME}
    - RDP username: ${WIN-USER}
    - RDP password: ${LABPASSWORD}

  + Amazone Linux 2 - victim host (admin-vm host): This EC2 is placed in an admin-vpc public subnet. It has AdministrtorAccess role
    - Public IP: ${LINUX-VICTIM_PUBIP}
    - Private IP: ${LINUX-VICTIM-PRIVIP}
    - Hostname: ${LIN_VICTIM_HOSTNAME}
    - username: ec2-user
    - use PEM file generated by this script at top-level folder (file name: ${KEYFILE})

- attacker-vpc
  + Windows 2019 Attacker host: This EC2 is placed in an attacker-vpc public subnet
    - Public IP: ${WIN-ATTACKER-PUBIP}
    - Private IP: ${WIN-ATTACKER-PRIVIP}
    - Hostname: ${LIN_ATTACKER_HOSTNAME}
    - RDP username: ${WIN-USER}
    - RDP password: ${LABPASSWORD}

  + Amazone Linux 2 - attacker host: This EC2 is placed in an attacker-vpc public subnet.
    - Public IP: ${LINUX-ATTACKER-PUBIP}
    - Private IP: ${LINUX-ATTACKER-PRIVIP}
    - Hostname: ${LIN_ATTACKER_HOSTNAME}
    - username: ec2-user
    - use PEM file generated by this script at top-level folder (file name: ${KEYFILE})

- There are CloudWatch log groups & Dashboard created for C1NS-appliances, you can check in AWS Cloudwatch console

- TMVWA is installed on Victim host, from attacker VM you can access to: http://${LINUX-VICTIM_PUBIP}
